apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2024-08-27T09:47:44Z"
  name: edge-web-server
  namespace: default
  resourceVersion: "7129"
  uid: 0c960b96-39d4-46d3-a63b-59d686c527ed
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-web-server