---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-web-server
  labels:
    app: edge-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          imagePullPolicy: "Always"
          image: hongtringuyen/web-server
          ports:
            - containerPort: 5000
          env:
            - name: PREPROCESSOR_SERVICE_PORT
              value: "8000"
            - name: SERVICE_NAME
              value: "edge-preprocessor"
          resources:
            requests:
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30004
  selector:
    app: web-server
  type: NodePort
