services:
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   ports:
  #     - "16686:16686" # Jaeger UI
  #     - "4317:4317"   # OTLP gRPC
  #     - "4318:4318"   # OTLP HTTP
  #   networks:
  #     - tracing-net
  #
  # otelcol:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: otelcol
  #   command: ["--config=/etc/otelcol-contrib/config.yaml"]
  #   volumes:
  #     - ./../config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - "4317:4317" # OTLP gRPC receiver
  #     - "4318:4318" # OTLP HTTP receiver
  #   networks:
  #     - tracing-net
  #   depends_on:
  #     - jaeger

  preprocessing:
    image: hongtringuyen/preprocessing
    container_name: preprocessing
    ports:
      - "5010:5010"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318}
    networks:
      - otel-net

  ensemble:
    image: hongtringuyen/ensemble
    container_name: ensemble
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318}
    networks:
      - otel-net

  efficientnetb0:
    image: hongtringuyen/inference
    container_name: efficientnetb0
    command: ["--model", "EfficientNetB0"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318}
    networks:
      - otel-net

  mobilenetv2:
    image: hongtringuyen/inference
    container_name: mobilenetv2
    command: ["--model", "MobileNetV2"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318}
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
