receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 2 # export spans in batches of 10
    timeout: 1000ms # send batch every 1 second if not full
    send_batch_max_size: 10 # max spans per batch

exporters:
  # use the OTLP exporter instance that targets Jaeger OTLP gRPC
  otlp/jaeger:
    endpoint: "jaeger:4317" # if running in same Docker network use service name
    tls:
      insecure: true # fine for local testing

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
